### ISSUE TITLE
Using with OPENCV Python

### ISSUE THREAD

**Issue by Avi241** [mprib/multiwebcam#30]
Is there any interface so that I can utilize this library with opencv python to get synchronized image from two USB camera for stereo.

**Comment by mprib** [comment]
@Avi241 ,

Thanks for your inquiry. I just created a little demo script that illustrates the general hierarchy used to organize "synchronized" frames:

https://github.com/mprib/multiwebcam/blob/main/dev/demo.py

I hope that this provides the tools you might need to work with this. If you have any questions, please just let me know. If this addresses your question, let me know too and I'll close this issue out...
